[package]
name = "tf2_rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
a2s = "0.5.1"
discord-rpc-client = "0.3.0"
sysinfo = "0.26.4"
rev_lines = "0.2.1"
steamlocate = "1.0.2"